# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93e2901b2309d64217538b85f4bd6676d0de57f5be48db4a93fa8f48f028ba6762fe4a33dae9756bc525c8bcb479911d5d9e62b8b9b31c02c6cf8297e0c237bc

test:
  secret_key_base: da5448ddbbb4bb2b37754fd24ee6435f38fe86dcb7d75ee28397d747e8ea13a12b59286004cd3ab90aa542bf82b6c46dccbc719846a756b9d3e27675bf3e04ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
